
@host = http://127.0.0.1:5120/api/applicant

POST {{host}}/create
Content-Type: application/json

{
  "firstName": "string",
  "middleName": "string",
  "lastName": "string",
  "birthDate": "2023-05-18T11:16:24.767Z",
  "gender": "Male",
  "passportNumber": "P33",
  "issuedDate": "2023-05-18T11:16:24.767Z",
  "passportExpiryDate": "2023-05-18T11:16:24.767Z",
  "placeOfBirth": "string",
  "amharicFullName": "string",
  "arabicFullName": "string",
  "complexion": "string",
  "numberOfChildren": 0,
  "motherName": "string",
  "previousNationality": "string",
  "currentNationality": "string",
  "height": 0,
  "weight": 0,
  "contractPeriod": 0,
  "amharicJobTitle": "string",
  "remark": "string",
  "isRequested": true,
  "isReserved": true,
  "isBlocked": true,
  "isDeleted": true,
  "issuingCountryId": "7d33be1d-1ee9-40b0-83b6-97f1f79c846d",
  "passportIssuedPlaceId": "ee0f3a62-3d1d-4ad6-81e9-6ba35888ec29",
  "maritalStatusId": "ea7b7d14-1771-4430-bfec-3b1c703d5d12",
  "healthId": "0468367a-4d6e-4eec-b34b-b67576dfa5c4",
  "religionId": "68ccacf6-c656-4447-b8cb-9a2f102f7e93",
  "jobtitleId": "90774ffc-e2f5-48f1-a20a-5fac0bfaacee",
  "experienceId": "02e12b3c-2377-43aa-81a0-699f7535cb1d",
  "languageId": "57f779bc-bbd4-457e-9737-1dbb2623bd3c",
  "salaryId": "fc6b063c-90f2-4f50-b2d1-f8fb1aa44ef6",
  "desiredCountryId": "7d33be1d-1ee9-40b0-83b6-97f1f79c846d",
  "brokerNameId": "3c0afa94-4d60-47fb-804a-92624785d035",
  "branchId": "9da90c6e-9bee-4b66-bf4b-f16161c87f8a",
  "partnerId": null,
  "languageSkills": [
    {
      "canWrite": true,
      "canRead": true,
      "canSpeak": true,
      "canListen": true,
      "proficiency": "No",
      "languageId": "57f779bc-bbd4-457e-9737-1dbb2623bd3c"
    }
  ],
  "skills": [
    "f38e9df7-edf3-44d8-9646-53c289c6daaa"
  ],
  "experiences": [
    {
      "periodLength": 0,
      "position": "string",
      "countryId": "7d33be1d-1ee9-40b0-83b6-97f1f79c846d"
    }
  ],
  "education": {
    "yearCompleted": 0,
    "fieldOfStudy": "string",
    "professionalSkill": "string",
    "qualificationTypes": [
      "a8bf96de-8c09-4e4e-a667-326bc84b8372"
    ],
    "levelofQualifications": [
      "dbb51fc9-c0f3-40c7-9468-4fafc977782f"
    ],
    "awards": [
      "2141ba2b-93fc-4939-b501-45adebba0754"
    ]
  },
  "bankAccount": {
    "bankName": "string",
    "accountNumber": 0,
    "branchName": "string",
    "swiftCode": "string"
  },
  "emergencyContact": {
    "firstName": "string",
    "middleName": "string",
    "lastName": "string",
    "birthDate": "2023-05-18T11:16:24.768Z",
    "gender": "Male",
    "arabicFullName": "string",
    "relationshipId": "7c652443-e3cd-4547-8ca0-f1a4af73bc07",
    "address": {
      "city": "string",
      "zone": "string",
      "woreda": "string",
      "kebele": "string",
      "phoneNumber": "string",
      "houseNumber": "string",
      "officePhone": "string",
      "mobile": "string",
      "alternativePhone": "string",
      "fax": "string",
      "adress": "string",
      "postCode": "string",
      "email": "string",
      "website": "string",
      "addressRegionId": "c01fc41e-2057-4e0b-b284-d720b698ea67"
    }
  },
  "representative": {
    "firstName": "string",
    "middleName": "string",
    "lastName": "string",
    "birthDate": "2023-05-18T11:16:24.768Z",
    "gender": "Male",
    "address": {
      "city": "string",
      "zone": "string",
      "woreda": "string",
      "kebele": "string",
      "phoneNumber": "string",
      "houseNumber": "string",
      "adress": "string"
    }
  },
  "witnesses": [
    {
      "firstName": "string",
      "middleName": "string",
      "lastName": "string",
      "address": "string",
      "phoneNumber": "string"
    }
  ],
  "beneficiaries": [
    {
      "firstName": "string",
      "middleName": "string",
      "lastName": "string",
      "region": "string",
      "zone": "string",
      "woreda": "string",
      "rate": 0,
      "relationshipId": "7c652443-e3cd-4547-8ca0-f1a4af73bc07"
    }
  ],
  "attachmentFiles": [
    {
      "filePath": "string",
      "attachmentId": "fce6ed27-5a20-4bc4-9701-e24c798552fb"
    }
  ],
  "address": {
    "city": "string",
    "zone": "string",
    "woreda": "string",
    "kebele": "string",
    "phoneNumber": "string",
    "houseNumber": "string",
    "officePhone": "string",
    "mobile": "string",
    "alternativePhone": "string",
    "fax": "string",
    "adress": "string",
    "postCode": "string",
    "email": "string",
    "website": "string",
    "addressRegionId": "c01fc41e-2057-4e0b-b284-d720b698ea67"
  }
}


###
GET http://localhost:5120/api/lookup/get-all-lookup?orderby=Value HTTP/1.1