
@host = http://192.168.1.25:8000/api/applicant

POST {{host}}/create
Content-Type: application/json

{
  "firstName": "Getahun",
  "middleName": "Shura",
  "lastName": "Gezachew",
  "birthDate": "2023-05-19T10:50:47.889Z",
  "gender": "Male",
  "passportNumber": "EP000006",
  "issuedDate": "2023-05-19T10:50:47.889Z",
  "passportExpiryDate": "2023-05-19T10:50:47.889Z",
  "placeOfBirth": "AA",
  "amharicFullName": "ጫላ አበበ ግዛቸው",
  "arabicFullName": "አል ነመራ",
  "complexion": "Brown",
  "numberOfChildren": 3,
  "motherName": "Alemitu",
  "previousNationality": "Ethiopian",
  "currentNationality": "Ethiopian",
  "height":160,
  "weight": 60,
  "contractPeriod": 3,
  "amharicJobTitle": "AmhJob title",
  "remark": "He is a good worker",
  "isRequested": false,
  "isReserved": false,
  "isBlocked": false,
  "isDeleted": false,
  "issuingCountryId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "passportIssuedPlaceId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "maritalStatusId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "healthId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "religionId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "jobtitleId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "experienceId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "languageId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "salaryId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "desiredCountryId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "brokerNameId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "branchId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "partnerId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
  "languageSkills": [
    {
      "canWrite": true,
      "canRead": true,
      "canSpeak": true,
      "canListen": true,
      "proficiency": "Good",
      "languageId": "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    }
  ],
  "skills": [
    "a986b11b-9569-48f2-a49a-4e9f4193a41b"
  ],
  "experiences": [
    {
      "periodLength": 2,
      "position": "SW Developer",
      "countryId": "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    }
  ],
  "education": {
    "yearCompleted": 2020,
    "fieldOfStudy": "SE",
    "professionalSkill": "Programming",
    "qualificationTypes": [
      "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    ],
    "levelofQualifications": [
      "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    ],
    "awards": [
      "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    ]
  },
  "bankAccount": {
    "bankName": "Dashen",
    "accountNumber": 1000263339413,
    "branchName": "Bole",
    "swiftCode": "DISHTTAA"
  },
  "emergencyContact": {
    "firstName": "Seboka",
    "middleName": "Jaleta",
    "lastName": "Dugasa",
    "birthDate": "1990-05-19T10:50:47.889Z",
    "gender": "Male",
    "arabicFullName": "ArabicFN",
    "relationshipId": "a986b11b-9569-48f2-a49a-4e9f4193a41b",
    "address": {
      "region": "Oromia",
      "city": "Dukem",
      "district": "string",
      "districtArabic": "string",
      "zone": "East Shoa",
      "woreda": "02",
      "kebele": "19",
      "street": "Ethio-Djibouti Railway",
      "streetArabic": "string",
      "phoneNumber": "+25175465647564",
      "houseNumber": "MK0022",
      "officePhone": "string",
      "mobile": "string",
      "alternativePhone": "string",
      "fax": "string",
      "adress": "Ethio-Djibouti Railway",
      "postCode": "string",
      "email": "string",
      "website": "string",
      "addressRegionId": "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    }
  },
  "representative": {
    "firstName": "Bakka Buusaa 2",
    "middleName": "Rep 2",
    "lastName": "Tewekay 2",
    "birthDate": "1993-05-19T10:50:47.889Z",
    "gender": "Male",
    "address": {
      "city": "AA",
      "zone": "Kality",
      "woreda": "09",
      "kebele": "12",
      "phoneNumber": "0987654321",
      "houseNumber": "string",
      "adress": "Ethio-China Friendship Square"
    }
  },
  "witnesses": [
    {
      "firstName": "Tola",
      "middleName": "Kabeta",
      "lastName": "Lmmessa",
      "address": "AA",
      "phoneNumber": "098765432"
    }
  ],
  "beneficiaries": [
    {
      "firstName": "Ben 1",
      "middleName": "string",
      "lastName": "string",
      "region": "string",
      "zone": "string",
      "woreda": "string",
      "rate": 13,
      "relationshipId": "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    }
  ],
  "attachmentFiles": [
    {
      "filePath": "D:\\Academic\\Test 1",
      "attachmentId": "a986b11b-9569-48f2-a49a-4e9f4193a41b"
    }
  ],
  "address": {
      "region": "Oromia",
      "city": "Dukem",
      "district": "string",
      "districtArabic": "string",
      "zone": "East Shoa",
      "woreda": "02",
      "kebele": "19",
      "street": "Ethio-Djibouti Railway",
      "streetArabic": "string",
      "phoneNumber": "+25175465647564",
      "houseNumber": "MK0022",
      "officePhone": "string",
      "mobile": "string",
      "alternativePhone": "string",
      "fax": "string",
      "adress": "Ethio-Djibouti Railway",
      "postCode": "string",
      "email": "string",
      "website": "string",
      "addressRegionId": "a986b11b-9569-48f2-a49a-4e9f4193a41b"
  }
}


###
GET {{host}}/get/22de630e-269e-415e-9282-f3747aefc6f6 HTTP/1.1


###
GET {{host}}/get-all HTTP/1.1
