
@host = http://127.0.0.1:5120/api/applicant

POST {{host}}/create
Content-Type: application/json

{
  "firstName": "Abebe",
  "middleName": "Lemma",
  "lastName": "Koricho",
  "birthDate": "2023-06-15T18:36:08.321Z",
  "gender": "Male",
  "passportNumber": "EP0001",
  "issuedDate": "2023-06-15T18:36:08.321Z",
  "passportExpiryDate": "2023-06-15T18:36:08.321Z",
  "placeOfBirth": "Finfinne",
  "amharicFullName":"አበበ ለማ ቆሪቾ",
  "arabicFullName": "string",
  "complexion": "Brown",
  "numberOfChildren": 0,
  "motherName": "Tigist",
  "previousNationality": "Eritrea",
  "currentNationality": "Ethiopia",
  "height": 172,
  "weight": 62,
  "contractPeriod": 2,
  "amharicJobTitle": "የቤት ሰራተኛ",
  "remark": "That is all about!",
  "issuingCountryId": "4788226b-3a2d-468f-9ad5-1388c74a20ef",
  "passportIssuedPlaceId": "3fbc7760-1673-467d-9892-db37fd48189b",
  "maritalStatusId": "29d9d6c9-c7f6-4880-a813-2db392b63cf2",
  "healthId": "97f74bda-9679-4701-b0c5-3cd23c84ade9",
  "religionId": "ab96fae6-99de-4fb5-8163-388faf9c4d6a",
  "jobtitleId": "8e846e5f-6b18-4643-adda-b0a7d0e730dc",
  "experienceId": "9792c804-ecf1-4204-96f8-e81ec17f5e98",
  "languageId": "ebc83e36-2fef-4e59-a34b-8026a6e2b1c1",
  "salaryId": "f106c7a0-bf91-4faa-bf08-8c6f44ee49aa",
  "desiredCountryId": "4788226b-3a2d-468f-9ad5-1388c74a20ef",
  "brokerNameId": "961dd3f5-7c3f-488e-af00-9cfe16f56840",
  "branchId": "e753a3a0-3517-422a-97eb-cf3a45688fc0",
  "partnerId": null,
  "skill": {
    "languageSkills": [
      {
        "canWrite": true,
        "canRead": true,
        "canSpeak": true,
        "canListen": true,
        "proficiency": "Good",
        "languageId": "ebc83e36-2fef-4e59-a34b-8026a6e2b1c1"
      }
    ],
    "skills": [
      "6b9366ab-26ca-4be3-a953-f029c03c381a"
    ]
  },
  "applicantExperience": {
    "experiences": [
      {
        "periodLength": 2,
        "position": "Software Engineering",
        "countryId": "4788226b-3a2d-468f-9ad5-1388c74a20ef"
      }
    ]
  },
  "education": {
    "yearCompleted": 2022,
    "fieldOfStudy": "SE",
    "professionalSkill": "Software Development",
    "qualificationTypes": [
      "e7fe69e5-29e5-4e28-8a0c-720610fad41a"
    ],
    "levelofQualifications": [
      "077ab8a3-1a76-4955-94f4-6e3a21ef21fd"
    ],
    "awards": [
      "53bb10a0-a778-4f9d-93ba-aae8b742c057"
    ]
  },
  "bankAccount": {
    "bankName": "CBE",
    "accountNumber": 1000263339413,
    "branchName": "Dukem",
    "swiftCode": "CBEETTAA"
  },
  "emergencyContact": {
    "nameOfContactPerson": "Tolcha",
    "arabicName": "string",
    "birthDate": "2023-06-15T18:36:08.321Z",
    "gender": "Male",
    "relationshipId": "96aa5fa6-12b9-43a7-a0b7-e0ed6c8fa4cb",
    "address": {
      "subCity": "Dukem",
      "zone": "East Shoa",
      "woreda": "Melka Dukem",
      "kebele": "01",
      "phoneNumber": "0912345678",
      "houseNumber": "MK001",
      "officePhone": "0912345678",
      "mobile": "0912345678",
      "alternativePhone": "0912345678",
      "fax": "04512345678",
      "adress": "Dukem, Ethio-Djibouti Railways",
      "postCode": "10001",
      "email": "abebe@email.com",
      "website": "abebe.com",
      "regionId": "46cb8844-0ac8-4c85-849e-5a616eeb8c5d"
    }
  },
  "witness": {
    "representative": {
      "fullName": "string",
      "city": "string",
      "zone": "string",
      "woreda": "string",
      "kebele": "string",
      "phoneNumber": "string",
      "houseNumber": "string"
    },
    "witnesses": [
      {
        "fullName": "string",
        "address": "string",
        "phoneNumber": "string"
      }
    ]
  },
  "beneficiary": {
    "beneficiaries": [
      {
        "fullName": "string",
        "region": "string",
        "zone": "string",
        "woreda": "string",
        "rate": 0,
        "relationshipId": "96aa5fa6-12b9-43a7-a0b7-e0ed6c8fa4cb"
      }
    ]
  },
  "attachment": {
    "attachmentFiles": [
      {
        "attachmentFile": "string",
        "attachmentId": null
      }
    ]
  },
  "address": {
      "subCity": "Dukem",
      "zone": "East Shoa",
      "woreda": "Melka Dukem",
      "kebele": "01",
      "phoneNumber": "0912345678",
      "houseNumber": "MK001",
      "officePhone": "0912345678",
      "mobile": "0912345678",
      "alternativePhone": "0912345678",
      "fax": "04512345678",
      "adress": "Dukem, Ethio-Djibouti Railways",
      "postCode": "10001",
      "email": "abebe@email.com",
      "website": "abebe.com",
      "regionId": "46cb8844-0ac8-4c85-849e-5a616eeb8c5d"
  }
}
