
@host = http://localhost:5120/api/applicant/

POST {{host}}/create
Content-Type: application/json

{
    "firstName": "Abebe",
    "middleName": "Balcha",
    "lastName": "Firomsa",
    "gender": "Male",
    "birthDate": "2023-04-30T18:27:18.967Z",
    "passportNumber": "EP00000001",
    "issuingCountry": "Ethiopia",
    "issuedDate": "2023-04-30T18:27:18.967Z",
    "issuedPlace": "Addis Ababa",
    "passportExpiryDate": "2023-04-30T18:27:18.967Z",
    "placeOfBirth": "Finfinne",
    "amharicFullName": "አበበ ባልቻ ፊሮምሳ",
    "arabicFullName": "string",
    "maritalStatus": "Single",
    "complexion": "Brown",
    "numberOfChildren": 0,
    "health": "Fit",
    "religionId": "85f05995-f9bc-4e86-8da8-2e0478940970",
    "jobTitles": [
        {
            "lookUpJobtitleId": "85f05995-f9bc-4e86-8da8-2e0478940970"
        }
    ],
    "salary": 875,
    "desiredCountry": "Saudi Arabia",
    "motherFullName": "Toltu Regassa",
    "previousCountry": "Ethiopia",
    "currentNationality": "Ethiopian",
    "height": 165,
    "contractPeriod": 3,
    "jobTitleAmharic": "የቤት ሰራተኛ",
    "brokerName": "ABH",
    "branch": "Bishoftu",
    "remark": "He is a good employee!",
    "languages": [
        {
        "languageId": "85f05995-f9bc-4e86-8da8-2e0478940970",
        "ability": {
                "canWrite": true,
                "canRead": true,
                "canSpeak": true,
                "canListen": true,
                "proficiency": "Good"
            }
        }
    ],
    "technicalSkills": [
        {
            "lookUpTechnicalSkillId": "85f05995-f9bc-4e86-8da8-2e0478940970"
        }
    ],
    "experiences": [
        {
            "countryLookupId": "85f05995-f9bc-4e86-8da8-2e0478940970",
            "periodLength": 5,
            "position": "House Maid"
        }
    ],
    "education": {
        "educationLevelofQualifications": [
            {
                "levelOfQualificationLookUpId": "85f05995-f9bc-4e86-8da8-2e0478940970"
            }
        ],
        "educationQualificationTypes": [
            {
                "qualificationTypeLookUpId": "85f05995-f9bc-4e86-8da8-2e0478940970"
            }
        ],
        "educationAawards": [
            {
                "awardLookUpId": "85f05995-f9bc-4e86-8da8-2e0478940970"
            }
        ],
        "yearCompleted": 2022,
        "fieldOfStudy": "SE",
        "professionalSkill": "Software Development"
    },
    "bankAccount": {
        "bankName": "CBE",
        "accountNumber": 1000263339413,
        "branchName": "Oda Nebe",
        "swiftCode": "CBEETTAA"
    },
    "emergencyContact": {
        "firstName": "Abebe",
        "middleName": "Lemma",
        "lastName": "Gutema",
        "relationship": "Uncle",
        "address": {
            "country": "Ethiopia",
            "region": "Oromia",
            "zone": "East Shoa",
            "woreda": "Akaki",
            "kebele": "Koticha",
            "phoneNumber": "+251912345678",
            "email": "abebe@email.com",
            "website": "abc.com"
        }
    },
    "repersentative": {
        "firstName": "Geresu",
        "middleName": "Hagos",
        "lastName": "Beressa",
        "address": {
            "country": "Ethiopia",
            "region": "Oromia",
            "zone": "East Shoa",
            "woreda": "Akaki",
            "kebele": "Koticha",
            "phoneNumber": "+251912345678",
            "email": "abebe@email.com",
            "website": "abc.com"
        }
    },
    "witnesses": [
        {
            "firstName": "Jenbere",
            "middleName": "Bonsa",
            "lastName": "Lemmi",
            "address": "Addis Ababa",
            "phoneNumber": "+251987654321"
        }
    ],
    "beneficiaries": [
        {
            "firstName": "Jitu",
            "middleName": "Getachew",
            "lastName": "Talema",
            "region": "Addis Ababa",
            "zone": "Kality",
            "woreda": "Akaki",
            "relationshipId": "85f05995-f9bc-4e86-8da8-2e0478940970",
            "rate": 35
        }
    ],
    "address": {
        "country": "Ethiopia",
        "region": "Oromia",
        "zone": "East Shoa",
        "woreda": "Akaki",
        "kebele": "Koticha",
        "phoneNumber": "+251912345678",
        "email": "abebe@email.com",
        "website": "abc.com"
    }
}

###


GET http://127.0.0.1:5120/api/lookup/get-all-lookup?pageNumber=1&pageSize=10&searchTerm=a&orderBy=Value&sortingDirection=Ascending HTTP/1.1
