

@host = http://127.0.0.1:5120/api/

PUT {{host}}/applicant/edit/1200b439-ac65-48ec-b5b5-3805cdc716a8
Content-Type: application/json

{
  "id": "1200b439-ac65-48ec-b5b5-3805cdc716a8",
  "firstName": "FN1",
  "middleName": "MN1",
  "lastName": "LN1",
  "birthDate": "2023-05-19T10:50:47.889Z",
  "gender": "Male",
  "passportNumber": "EP000005",
  "issuedDate": "2023-05-19T10:50:47.889Z",
  "passportExpiryDate": "2023-05-19T10:50:47.889Z",
  "placeOfBirth": "AA",
  "amharicFullName": "ጫላ አበበ ግዛቸው",
  "arabicFullName": "አል ነመራ",
  "complexion": "Brown",
  "numberOfChildren": 3,
  "motherName": "Chaltu",
  "previousNationality": "Ethiopian",
  "currentNationality": "Ethiopian",
  "height":160,
  "weight": 60,
  "contractPeriod": 3,
  "amharicJobTitle": "AmhJob title",
  "remark": "He is a good worker",
  "isRequested": false,
  "isReserved": false,
  "isBlocked": true,
  "isDeleted": false,
  "issuingCountryId": "e21f9284-c916-4b50-865f-fdeff0731ebc",
  "passportIssuedPlaceId": "e77884eb-89db-49eb-8ffd-1579ffa607bb",
  "maritalStatusId": "5da51288-d243-4882-acd5-66d9e21faeb9",
  "healthId": "86bba764-a52e-4e1a-a767-1c64f4cc2353",
  "religionId": "5255916b-7f80-47fb-9671-ef58e97dc4ba",
  "jobtitleId": "d914296b-fb04-45e8-a127-26ca4ba17778",
  "experienceId": "348ee93d-c1e2-44c7-93b8-2b5ad5116ef7",
  "languageId": "fd472986-1cff-4d10-b421-8ded83039c37",
  "salaryId": "809fbd76-6e42-48c9-9f4b-e6b8b58d3f9b",
  "desiredCountryId": "e21f9284-c916-4b50-865f-fdeff0731ebc",
  "brokerNameId": "578c7f2b-27b0-4b2a-9826-216b11652973",
  "branchId": "d8571412-e0a0-436b-a18d-80b6ee4f6de6",
  "partnerId": "01160ed8-18f4-4887-92ac-10d667f42868",
  "languageSkills": [
    {
      "id": "be39a36f-b04b-49ad-b5e0-91bb19a7a2c0",
      "canWrite": true,
      "canRead": false,
      "canSpeak": false,
      "canListen": true,
      "proficiency": "Good",
      "languageId": "fd472986-1cff-4d10-b421-8ded83039c37"
    }
  ],
  "skills": [
    "826d7ff9-dac6-4286-bbb6-f4e0277240a8"
  ],
  "experiences": [
    {
      "id": "5ee2c121-cd92-473f-813e-a8c1009c2750",
      "periodLength": 4,
      "position": "System Administrator",
      "countryId": "e21f9284-c916-4b50-865f-fdeff0731ebc"
    }
  ],
  "education": {
    "id": "873548a0-1755-47e6-bfb1-287061a9448e",
    "yearCompleted": 2014,
    "fieldOfStudy": "CS",
    "professionalSkill": "No Skill",
    "qualificationTypes": [
      "a8bf96de-8c09-4e4e-a667-326bc84b8372"
    ],
    "levelofQualifications": [
      "dbb51fc9-c0f3-40c7-9468-4fafc977782f"
    ],
    "awards": [
      "2141ba2b-93fc-4939-b501-45adebba0754"
    ]
  },
  "bankAccount": {
    "id": "f2d04719-ad68-4e82-b08f-a53816679980",
    "bankName": "Dashen",
    "accountNumber": 1000263339413,
    "branchName": "Bole",
    "swiftCode": "DISHTAA"
  },
  "emergencyContact": {
    "id": "dce47efd-9165-4d1a-a73c-e6dc5d721ccb",
    "firstName": "ECF1",
    "middleName": "ECM1",
    "lastName": "ECL1",
    "birthDate": "1990-05-19T10:50:47.889Z",
    "gender": "Male",
    "arabicFullName": "ArabicFN",
    "relationshipId": "c0fe6c0e-1512-4e3f-956d-46645844e167",
    "address": {
      "id": "da2616b9-8bb0-4b34-9321-6e9ade6ed0b2",
      "region": "ECAR1",
      "city": "ECAC1",
      "district": "string",
      "districtArabic": "string",
      "zone": "East Shoa",
      "woreda": "02",
      "kebele": "19",
      "street": "Ethio-Djibouti Railway",
      "streetArabic": "string",
      "phoneNumber": "+25175465647564",
      "houseNumber": "MK0021",
      "officePhone": "string",
      "mobile": "string",
      "alternativePhone": "string",
      "fax": "string",
      "adress": "Ethio-Djibouti Railway",
      "postCode": "string",
      "email": "string",
      "website": "string",
      "addressRegionId": "6d030bc0-3dd3-40a3-a49e-abfcb222a47f"
    }
  },
  "representative": {
    "id": "9088e981-537b-4774-8217-2b3f20618ff5",
    "firstName": "RF1",
    "middleName": "RM1",
    "lastName": "RL1",
    "birthDate": "1993-05-19T10:50:47.889Z",
    "gender": "Male",
    "address": {
      "id": "de7e9a7b-c3a2-4e25-a1a6-6d892f5bb468",
      "city": "RAC1",
      "zone": "Kality",
      "woreda": "09",
      "kebele": "12",
      "phoneNumber": "0987654321",
      "houseNumber": "string",
      "adress": "Ethio-China Friendship Square"
    }
  },
  "witnesses": [
    {
      "id": "da7f8422-5157-4c6e-be03-bd5a5e36d00f",
      "firstName": "WF1",
      "middleName": "string",
      "lastName": "string",
      "address": "string",
      "phoneNumber": "string"
    }
  ],
  "beneficiaries": [
    {
      "id": "0e9fef6e-7462-400b-8b4e-0f1d75509ede",
      "firstName": "BENF1",
      "middleName": "string",
      "lastName": "string",
      "region": "string",
      "zone": "string",
      "woreda": "string",
      "rate": 12,
      "relationshipId": "c0fe6c0e-1512-4e3f-956d-46645844e167"
    }
  ],
  "attachmentFiles": [
    {
      "id": "be1c1313-3bae-47ba-8152-b136b29090b7",
      "filePath": "D:\\Academic\\Tests2",
      "attachmentId": "011f0ed8-18f4-4887-92ac-10d667f42868"
    }
  ],
  "address": {
      "id": "b6ed5b19-b54b-4aac-bb19-94cdf11fe1ec",
      "region": "AA1",
      "city": "Bishoftu",
      "district": "string",
      "districtArabic": "string",
      "zone": "East Shoa",
      "woreda": "02",
      "kebele": "19",
      "street": "Ethio-Djibouti Railway",
      "streetArabic": "string",
      "phoneNumber": "+25175465647564",
      "houseNumber": "MK0021",
      "officePhone": "string",
      "mobile": "string",
      "alternativePhone": "string",
      "fax": "string",
      "adress": "Ethio-Djibouti Railway",
      "postCode": "string",
      "email": "string",
      "website": "string",
      "addressRegionId": "6d030bc0-3dd3-40a3-a49e-abfcb222a47f"
  }
}

###
PUT http://127.0.0.1:5120/api/applicant/request/1200b439-ac65-48ec-b5b5-3805cdc716a8 

###
GET http://127.0.0.1:5120/api/applicant/get/1200b439-ac65-48ec-b5b5-3805cdc716a8 
###
GET http://localhost:5120/api/applicant/get-all-requested HTTP/1.1
