
@host = http://localhost:5120/api/applicant

POST {{host}}/create
Content-Type: application/json

{
  "firstName": "alewiya",
  "middleName": "kedr",
  "lastName": "Koricho",
  "birthDate": "2023-06-15T18:36:08.321Z",
  "gender": "female",
  "passportNumber": "EP0001",
  "issuedDate": "2023-06-15T18:36:08.321Z",
  "passportExpiryDate": "2023-06-15T18:36:08.321Z",
  "placeOfBirth": "Finfinne",
  "amharicFullName":"kebede ለማ ቆሪቾ",
  "arabicFullName": "string",
  "complexion": "Brown",
  "numberOfChildren": 0,
  "motherName": "Tigist",
  "previousNationality": "Eritrea",
  "currentNationality": "Ethiopia",
  "height": 172,
  "weight": 62,
  "contractPeriod": 2,
  "amharicJobTitle": "የቤት ሰራተኛ",
  "remark": "That is all about!",
  "issuingCountryId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "passportIssuedPlaceId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "maritalStatusId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "healthId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "religionId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "jobtitleId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "experienceId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "languageId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "salaryId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "desiredCountryId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "brokerNameId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "branchId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
  "partnerId": null,
  "skill": {
    "languageSkills": [
      {
        "canWrite": true,
        "canRead": true,
        "canSpeak": true,
        "canListen": true,
        "proficiency": "Good",
        "languageId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
      }
    ],
    "skills": [
      "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
    ]
  },
  "applicantExperience": {
    "experiences": [
      {
        "periodLength": 2,
        "position": "Software Engineering",
        "countryId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
      }
    ]
  },
  "education": {
    "yearCompleted": 2022,
    "fieldOfStudy": "SE",
    "professionalSkill": "Software Development",
    "qualificationTypes": [
      "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
    ],
    "levelofQualifications": [
      "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
    ],
    "awards": [
      "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
    ]
  },
  "bankAccount": {
    "bankName": "CBE",
    "accountNumber": 1000263339413,
    "branchName": "Dukem",
    "swiftCode": "CBEETTAA"
  },
  "emergencyContact": {
    "nameOfContactPerson": "Tolcha",
    "arabicName": "string",
    "birthDate": "2023-06-15T18:36:08.321Z",
    "gender": "Male",
    "relationshipId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda",
    "address": {
      "subCity": "Dukem",
      "zone": "East Shoa",
      "woreda": "Melka Dukem",
      "kebele": "01",
      "phoneNumber": "0912345678",
      "houseNumber": "MK001",
      "officePhone": "0912345678",
      "mobile": "0912345678",
      "alternativePhone": "0912345678",
      "fax": "04512345678",
      "adress": "Dukem, Ethio-Djibouti Railways",
      "postCode": "10001",
      "email": "abebe@email.com",
      "website": "abebe.com",
      "regionId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
    }
  },
  "witness": {
    "representative": {
      "fullName": "string",
      "city": "string",
      "zone": "string",
      "woreda": "string",
      "kebele": "string",
      "phoneNumber": "string",
      "houseNumber": "string"
    },
    "witnesses": [
      {
        "fullName": "string",
        "address": "string",
        "phoneNumber": "string"
      }
    ]
  },
  "beneficiary": {
    "beneficiaries": [
      {
        "fullName": "string",
        "region": "string",
        "zone": "string",
        "woreda": "string",
        "rate": 10,
        "relationshipId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
      }
    ]
  },
  "attachment": {
    "orderId": null,
    "attachmentFiles": [
      
    ]
  },
  "address": {
      "subCity": "Dukem",
      "zone": "East Shoa",
      "woreda": "Melka Dukem",
      "kebele": "01",
      "phoneNumber": "0912345678",
      "houseNumber": "MK001",
      "officePhone": "0912345678",
      "mobile": "0912345678",
      "alternativePhone": "0912345678",
      "fax": "04512345678",
      "adress": "Dukem, Ethio-Djibouti Railways",
      "postCode": "10001",
      "email": "abebe@email.com",
      "website": "abebe.com",
      "regionId": "e8267e0a-4dfc-4ba3-b2da-ac3545741bda"
  }
}


###
GET {{host}}/get/22de630e-269e-415e-9282-f3747aefc6f6 HTTP/1.1


###
GET {{host}}/get-all HTTP/1.1
