
@host = http://127.0.0.1:5120/api/attachment

GET {{host}}/get-all HTTP/1.1

###
POST {{host}}/create
Content-Type: application/json

{
    "attachment": {
        "code": "Passport",
        "description": "Passport Attachment",
        "category": 5,
        "isRequired": true,
        "showOnCv": false
    }
}


###

DELETE {{host}}/delete
Content-Type: application/json

{
    "id":"5a6df12b-03d0-4ce2-b6b9-c96d56e7bf27"
}

###
PUT {{host}}/edit/5a6df12b-03d0-4ce2-b6b9-c96d56e7bf27
Content-Type: application/json

{
    "id":"5a6df12b-03d0-4ce2-b6b9-c96d56e7bf27",
    "code": "Passport",
    "description": "Passport Attachment",
    "category": "OrderAttachment",
    "isRequired": true,
    "showOnCv": false
}
