@host = http://127.0.0.1:5120/api

POST {{host}}/order/create HTTP/1.1
Content-Type: application/json

{
  "orderNumber": "O004",
  "visaNumber": "VS004",
  "contractDuration": 2,
  "visaDate": "2023-05-22T11:33:07.847Z",
  "orderDate": "2023-05-22T11:33:07.847Z",
  "contractNumber": "string",
  "electronicVisaNumber": "string",
  "electronicVisaDate": "2023-05-22T11:33:07.847Z",
  "portOfArrivalId": "c5302c62-c535-4a9a-a4bc-ddf7aa3bf7be",
  "priorityId": "8cee4417-5506-48c2-942b-e033962994f1",
  "visaTypeId": "f617f3f7-3771-4cef-b19e-d7e52bd6b2ce",
  "employeeId": null,
  "partnerId": "01160ed8-18f4-4887-92ac-10d667f42868",
  "attachmentFile": {
    "filePath": "string",
    "attachmentId": "cfe2a440-5ab4-469b-803c-956147153e09"
  },
  "orderCriteria": {
    "age": 20,
    "remark": "string",
    "nationalityId": "bdc2c6f6-3dd3-4b05-ba7b-c33723071a7c",
    "jobTitleId": "90774ffc-e2f5-48f1-a20a-5fac0bfaacee",
    "salaryId": "fc6b063c-90f2-4f50-b2d1-f8fb1aa44ef6",
    "religionId": "68ccacf6-c656-4447-b8cb-9a2f102f7e93",
    "experienceId": "02e12b3c-2377-43aa-81a0-699f7535cb1d",
    "languageId": "57f779bc-bbd4-457e-9737-1dbb2623bd3c"
  },
  "payment": {
    "totalAmount": 2600,
    "currentPaidAmount": 1000
  },
  "sponsor": {
    "idNumber": "P004",
    "fullName": "string",
    "fullNameAmharic": "string",
    "fullNameArabic": "string",
    "otherName": "string",
    "residentialTitle": "string",
    "numberOfFamily": 0,
    "attachmentFile": {
      "filePath": "Atch004",
      "attachmentId": "cfe2a440-5ab4-469b-803c-956147153e09"
    },
    "address": {
      "city": "Jeddah",
      "zone": "string",
      "woreda": "string",
      "kebele": "string",
      "phoneNumber": "string",
      "houseNumber": "string",
      "officePhone": "string",
      "mobile": "string",
      "alternativePhone": "string",
      "fax": "string",
      "adress": "Add004",
      "postCode": "string",
      "email": "string",
      "website": "string",
      "addressRegionId": "c01fc41e-2057-4e0b-b284-d720b698ea67"
    }
  }
}

###
GET {{host}}/order/get-all HTTP/1.1