@host = http://127.0.0.1:5120/api

POST {{host}}/order/create HTTP/1.1
Content-Type: application/json

{
  "orderNumber": "OR1234",
  "visaNumber": "VS1234",
  "contractDuration": 2,
  "visaDate": "2023-07-14T06:25:19.374Z",
  "orderDate": "2023-07-14T06:25:19.374Z",
  "contractNumber": "string",
  "electronicVisaNumber": "string",
  "electronicVisaDate": "2023-07-14T06:25:19.374Z",
  "portOfArrivalId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
  "priorityId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
  "visaTypeId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
  "employeeIds": [
    "65e42b7b-5e5d-4b24-95f1-d2fcabddeadd"
  ],
  "partnerId": "2db214f7-d4c8-4c1f-b707-0cb6053c4e6c",
  "attachmentFile":null,
  "orderCriteria": {
    "age": 0,
    "remark": "string",
    "nationalityId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
    "jobTitleId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
    "salaryId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
    "religionId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
    "experienceId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
    "languageId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1"
  },
  "payment": {
    "totalAmount": 1500,
    "currentPaidAmount": 900
  },
  "sponsor": {
    "idNumber": "DP0001",
    "fullName": "AbdulQadir",
    "fullNameAmharic": "string",
    "fullNameArabic": "string",
    "otherName": "string",
    "residentialTitle": "Mr.",
    "numberOfFamily": 3,
    "attachmentFile": null,
    "address": {
      "street": "Riyadh",
      "phoneNumber": "+9961234567",
      "houseNumber": "string",
      "officePhone": "+9961234567",
      "mobile": "+9961234567",
      "alternativePhone": "+9961234567",
      "fax": "+9961234567",
      "adress": "Riyadh",
      "postCode": "+9961234567",
      "email": "abdulqadir@gmail.com",
      "website": "abdulqadir.com",
      "countryId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1",
      "cityId": "7144e9e0-baea-4fa3-bbe6-b3be7e473be1"
    }
  }
}

###
GET {{host}}/order/get-all HTTP/1.1