@host = http://127.0.0.1:5120/api

###

PUT {{host}}/order/edit
Content-Type:  application/json

{
  "editOrderRequest": {
    "id": "7340ce80-a181-4caa-a06e-813086f57482",
    "orderNumber": "OR0002",
    "visaNumber": "VS0002",
    "contractDuration": 4,
    "visaDate": "2023-05-08T12:46:35.961Z",
    "contractNumber": "91324567287",
    "electronicVisaNumber": "EV0002",
    "electronicVisaDate": "2023-05-08T12:46:35.961Z",
    "portOfArrivalId": "e89be5ff-4c0b-42f3-9b23-91c82a01feeb",
    "priorityId": "3fa2a4ea-4e36-4482-8aca-6cd13cd664be",
    "visaTypeId": "6caf9eab-c22c-438f-b7b6-98f31a514c7e",
    "visaFile": {
      "id": "ebb20a09-f0fd-41f2-9440-5bd94b3ea658",
      "fileCollectionAttachmentId": "dca4df58-f503-4e3a-aec8-95a474599363",
      "filePath": "D:\\TestRequest\\FileCollections"
    },
    "orderCriteria": {
      "id": "08db5185-d340-4d41-8686-c30a5fdff8a6",
      "age": 25,
      "nationalityId": "8cf0c6c3-2850-4351-932d-31f9dc3bbbc3",
      "orderCriteriaJobTitleId": "90774ffc-e2f5-48f1-a20a-5fac0bfaacee",
      "salaryId": "da86ba94-de5c-4f3d-a04f-e4ee0c2c7b1d",
      "religionId": "68ccacf6-c656-4447-b8cb-9a2f102f7e93",
      "experienceId": "68848f4e-19eb-4b19-9eb9-7ab3e0ab6770",
      "languageId": "57f779bc-bbd4-457e-9737-1dbb2623bd3c",
      "remark": "Demo request 4"
    },
    "orderPayment": {
      "id": "08db5185-d347-4f95-8b94-2955ab3fde4b",
      "totalAmount": 800,
      "paidAmount": 400,
      "currentPaidAmount": 300
    },
    "orderSponsor": {
      "id": "08db5185-d349-4729-8de2-985ffe38a846",
      "idNumber": "SP0004",
      "fullName": "Al Shugah Khareem",
      "fullNameAmharic": "አል A",
      "otherName": "string",
      "residentialTitle": "string",
      "numberOfFamily": 7,
      "sponsorIDFile": {
        "id": "d5c013d9-e463-4ae0-b07d-3ec6d0d8f4d2",
        "fileCollectionAttachmentId": "dca4df58-f503-4e3a-aec8-95a474599363",
        "filePath": "D:\\RequestTest\\FileCollections"
      },
      "sponsorAddress": {
        "id": "f751c8c4-0571-4740-a055-d0b72b1eb2d5",
        "addressCountryId": "7d33be1d-1ee9-40b0-83b6-97f1f79c846d",
        "region": "Jeddah",
        "zone": "Jeddah",
        "woreda": "05",
        "kebele": "14",
        "phoneNumber": "+966123456678",
        "email": "alshayeer@gmail.com",
        "website": "abc.com"
      }
    }
  }
}

###
{{host}}/lookup/get-all-lookup?pageNumber=1&pageSize=100&orderBy=Value&sortingDirection=Ascending